name: Build and Release Binaries

on:
  push:
    tags:
      - 'v*'   # e.g., v1.0.0

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Linux x86_64
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            archive: tar.gz
            bin_ext: ""

          # Linux ARM64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            archive: tar.gz
            bin_ext: ""

          # Windows x86_64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            archive: zip
            bin_ext: ".exe"

          # Windows ARM64
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            archive: zip
            bin_ext: ".exe"

          # macOS Intel
          - os: macos-latest
            target: x86_64-apple-darwin
            archive: zip
            bin_ext: ""

          # macOS Apple Silicon
          - os: macos-latest
            target: aarch64-apple-darwin
            archive: zip
            bin_ext: ""

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Install cross-compilation tools (Linux ARM64)
        if: matrix.target == 'aarch64-unknown-linux-gnu' && runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Install cross-compilation tools (Windows ARM64)
        if: matrix.target == 'aarch64-pc-windows-msvc' && runner.os == 'Windows'
        run: |
          # Windows ARM64 cross-compilation is natively supported by MSVC
          # No additional tools needed, but ensure the correct build tools are available
          echo "Windows ARM64 cross-compilation enabled via MSVC"

      - name: Install cross-compilation tools (macOS)
        if: (matrix.target == 'aarch64-apple-darwin' || matrix.target == 'x86_64-apple-darwin') && runner.os == 'macOS'
        run: |
          # macOS supports universal binaries and cross-compilation natively
          # No additional tools needed on modern macOS with Xcode
          echo "macOS cross-compilation enabled"

      - name: Build binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Prepare archive
        shell: bash
        run: |
          mkdir -p dist
          BIN_NAME="build-it-agent${{ matrix.bin_ext }}"
          BIN_PATH="target/${{ matrix.target }}/release/$BIN_NAME"

          if [ ! -f "$BIN_PATH" ]; then
            echo "Error: Binary not found at $BIN_PATH"
            exit 1
          fi

          cp "$BIN_PATH" "dist/"
          cd dist

          ARCHIVE_NAME="${BIN_NAME%.*}-${{ matrix.target }}.${{ matrix.archive }}"

          if [ "${{ matrix.archive }}" = "zip" ]; then
            zip -r "$ARCHIVE_NAME" "$BIN_NAME"
          else
            tar -czf "$ARCHIVE_NAME" "$BIN_NAME"
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: dist/*

  release:
    name: Publish GitHub Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Display structure (debug)
        run: ls -R dist

      - name: Create checksums
        run: |
          cd dist
          find . -type f -exec sha256sum "{}" \; > checksums.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**/*.zip
            dist/**/*.tar.gz
            dist/checksums.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
